### ISSUE TITLE
Communication through the system

### ISSUE THREAD

**Issue by agbeltran** [softwaresaved/lowfat#440] opened 2018-04-16 17:16 UTC
In a specific funding request, the messages from SSI to the fellow are listed. It seems it is not possible for a fellow to send a message related to the specific funding request through the system. Maybe this would be a useful functionality to add? Thanks

**Comment by rgaiacs** [comment] 2018-04-17 09:04
> In a specific funding request, the messages from SSI to the fellow are listed.

We did this for record keeping so that staff and fellows know any email that the system sent.

> It seems it is not possible for a fellow to send a message related to the specific funding request through the system. Maybe this would be a useful functionality to add?

We didn't add the option for fellows to sent message from the system because this will increase the complexity of the code and open the question of why not allow a reply by email that the system can record.

Thanks very much for the suggestion. I will discuss this with other staff.

**Comment by rgaiacs** [comment] 2019-05-01 16:40
Duplicate of softwaresaved/lowfat#442

**Closed by rgaiacs** 2019-05-01 16:40 UTC
Labels: enhancement
